# Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Importing the data

In [18]:
data = pd.read_csv('insurance.csv')
x = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [19]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

# Encoding categorical data

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
coltran = ColumnTransformer([('encoder', OneHotEncoder(), [1, 4, 5])], remainder = 'passthrough')
x = np.array(coltran.fit_transform(x))

In [31]:
print(x)

[[1.0 0.0 0.0 ... 19 27.9 0]
 [0.0 1.0 0.0 ... 18 33.77 1]
 [0.0 1.0 0.0 ... 28 33.0 3]
 ...
 [1.0 0.0 0.0 ... 18 36.85 0]
 [1.0 0.0 0.0 ... 21 25.8 0]
 [1.0 0.0 1.0 ... 61 29.07 0]]


In [32]:
print(y)

[16884.92  1725.55  4449.46 ...  1629.83  2007.94 29141.36]


# Splitting data into training and test set

In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

# Training the training set and predicting the test set

In [34]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [35]:
y_predict = regressor.predict(x_test)
np.set_printoptions(precision = 2)
print(np.concatenate((y_predict.reshape(len(y_predict), 1), y_test.reshape(len(y_test), 1,)), 1))

[[1.12e+04 9.72e+03]
 [9.49e+03 8.55e+03]
 [3.82e+04 4.57e+04]
 [1.63e+04 1.30e+04]
 [6.91e+03 9.64e+03]
 [3.96e+03 4.50e+03]
 [1.58e+03 2.20e+03]
 [1.44e+04 1.14e+04]
 [9.01e+03 7.54e+03]
 [7.51e+03 5.43e+03]
 [4.49e+03 6.75e+03]
 [1.03e+04 1.05e+04]
 [8.80e+03 7.34e+03]
 [3.80e+03 4.19e+03]
 [2.79e+04 1.83e+04]
 [1.07e+04 1.07e+04]
 [1.13e+04 1.25e+04]
 [6.11e+03 3.49e+03]
 [8.24e+03 6.46e+03]
 [2.71e+04 3.35e+04]
 [3.36e+04 2.40e+04]
 [1.44e+04 1.26e+04]
 [1.17e+04 2.30e+04]
 [3.21e+04 2.31e+04]
 [4.17e+03 1.67e+03]
 [9.25e+03 4.67e+03]
 [1.08e+03 3.73e+03]
 [9.80e+03 7.68e+03]
 [3.77e+03 3.76e+03]
 [1.04e+04 8.41e+03]
 [9.01e+03 8.06e+03]
 [4.01e+04 4.90e+04]
 [1.57e+04 1.30e+04]
 [1.39e+04 2.06e+04]
 [2.48e+04 1.46e+04]
 [5.17e+03 4.14e+03]
 [1.26e+04 8.35e+03]
 [3.08e+04 5.12e+04]
 [3.35e+04 4.00e+04]
 [3.67e+03 1.88e+03]
 [3.98e+03 5.46e+03]
 [3.99e+03 2.87e+03]
 [3.05e+04 2.01e+04]
 [3.95e+04 4.75e+04]
 [2.78e+04 3.61e+04]
 [5.09e+03 2.60e+04]
 [1.06e+04 1.97e+04]
 [7.83e+03 6.

In [40]:
print(regressor.predict([[0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 25, 20.0, 0]]))
print(regressor.coef_)
print(regressor.intercept_)

[1186.14]
[ 3.87e+00 -3.87e+00  9.32e+01 -9.32e+01 -9.32e+01  9.32e+01  3.87e+00
 -3.16e+02  3.16e+02  3.87e+00 -1.18e+04  1.18e+04 -2.80e+02 -1.29e+02
  2.54e+02  3.36e+02  4.37e+02]
-167.22906578668335
